/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 barrel.gltf 
Author: niver_mk (https://sketchfab.com/niver_mk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wine-barrel-5b7aefe2295f4ea5953bccb970ae76c0
Title: Wine Barrel
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('3d_model/wine_barrel/barrel.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.barrel_Barrel_material_0.geometry} material={materials.Barrel_material} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.stand_Barrel_material_0.geometry} material={materials.Barrel_material} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.bung_Barrel_material_0.geometry} material={materials.Barrel_material} position={[0, 70.109, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.valve_Barrel_material_0.geometry} material={materials.Barrel_material} position={[0, 18.506, 42.211]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.rings_Barrel_material_0.geometry} material={materials.Barrel_material} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/barrel.gltf')
